name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./ # flydiverny/github-typescript@main
        name: Testing MTS extension
        env:
          INPUT_SOMETHING: "Nice *.mts demo run"
        with:
          script-file: .github/workflows/script.mts

      - uses: ./ # flydiverny/github-typescript@main
        name: Testing TS extension
        env:
          INPUT_SOMETHING: "Nice *.ts demo run"
        with:
          script-file: .github/workflows/script.ts
